data:
  image: tianon/true
  container_name: mariadb_data
  volumes:
    - /var/lib/mysql

server:
  build: server
  container_name: mariadb_server
  log_driver: syslog
  log_opt:
    address: "udp://127.0.0.1:514"
  ports:
    - "0.0.0.0:3306:3306/tcp"
  restart: always
  volumes_from:
    - data
